src/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView


from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),    
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('profiel/<int:pk>/',views.Profiel_edit.as_view(), name='profiel_edit'),
    path('profiel/<int:pk>/detail/', views.DetailProfiel.as_view(), name='profiel_detail'),
]

src/book/urls.py
from django.urls import path
# from .views import ListBook, DetailBook,CreateBook,UpdateBook,DeleteBook,IndexBook

from . import views


urlpatterns = [
    path('', views.IndexBook.as_view(), name='index'),
    path('list/', views.ListBook.as_view(), name='booklist'),
    path('listtable/', views.ListTableBook.as_view(), name='booktable'),
    path('detail/<int:pk>/', views.DetailBook.as_view(), name='detail'),
    path('create/', views.CreateBook.as_view(), name='create'),
    path('update/<int:pk>/', views.UpdateBook.as_view(), name='update'),
    path('delete/<int:pk>/', views.DeleteBook.as_view(), name='delete'),
    path('comment/<int:pk>', views.ReviewCreate.as_view(), name='new_comment'),
]

src/main/urls.py
import debug_toolbar 
from django.conf import settings 
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('staff-admin-homan/', admin.site.urls),
    path('accounts/', include('allauth.urls')), #これ追加
    path('app_accounts/', include('accounts.urls')),
    path('',include('book.urls')),
    path('__ debug __ /', include(debug_toolbar.urls))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/templateh/css.html
{% load static %}
<!-- boxicons CSS -->
<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

<!-- ファビコン？ -->
<link rel="shortcut icon" href="favicon.ico">

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css"><!--アイコン用-->

<!--フォント-->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Kaisei+Opti:wght@400;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static '/css/base.css' %}">

src/templates/templateh/footer.html
<!--footer-->
      <section>
      
        <footer id="footer">
          <div class="footer_group">
            <div class="line">
              
               <div class="footer_icon">
                <a href="#">  
                  <i class='bx bxs-book-bookmark'></i>
                </a>
              </div>
            
            </div>
            <div class="text-link">
              <a href="#">
                プライバシーポリシー
              </a>
              |
              <a href="#">
                 利用規約
              </a>        
              |
              <small>Copyright &copy; 2021 yulikepython</small>
            </div>       
          </div>
        </div>
        </footer>
    </section>

src/templates/templateh/js.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

src/templates/templateh/messages.html
{% for message in messages %}
    {% if message.tags == "error" %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% else %}
    <div {% if message.tags %}class="alert alert-{{ message.tags }} alert-dismissible fade show"{% endif %} role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}
    {% endfor %}

src/templates/templateh/nav.html
<!--nav.html タグ継承 現在はincludeしてない-->
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark pt-3 pb-3">
    <div class="container d-flex">
      <h2 class="text-white ps-5">
          Bookアプリ
      </h2>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Topページ</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'booklist' %}">Book一覧</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'create' %}">Book作成</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              プロフィール
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><a class="dropdown-item" href="{% url 'accounts:profiel_edit' request.user.profiels.pk %}">プロフィール編集</a></li>
              <li><a class="dropdown-item" href="{% url 'accounts:profiel_detail' request.user.profiels.pk %}">プロフィール詳細</a></li>
            </ul>
          
          </li>
          {% endif %}
          {% block nav %}{% endblock nav %}
          
        
        
          {% if request.user.is_authenticated %}
          <li class="nav-item active">
          <a href="{% url 'accounts:logout' %}" class="text-white btn btn-primary my-1 mx-2">ログアウト</a>
          </li>
          {% else %}
          <li class="nav-item active">
          <a href="{% url 'account_login' %}" class="text-white btn btn-primary my-1 mx-2">ログイン</a>
          </li>
          {% endif %}
          <li class="nav-item active">
          <a href="{% url 'account_signup' %}" class="text-white btn btn-primary my-1 mx-2">会員登録</a>
          </li>
        </ul>
      </div>
    </div>  
  </nav>
</header>